baseURL = "https://lewta.github.io/sendit/"
title = "sendit"
enableGitInfo = true

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[params.docs]
  title           = "sendit"
  themeColor      = "blue"
  darkMode        = true
  breadcrumbs     = true
  descriptions    = true
  backToTop       = true

  [params.docs.gitInfo]
    repoURL     = "https://github.com/lewta/sendit"
    repoBranch  = "main"
    editPage    = false
    lastMod     = true
    lastModRelative = true
